# Phase 1

# Analyse explorative des données :

In [36]:
import numpy as np
import pandas as pd 
data=pd.read_csv('Phase1.csv')
data.info() # Voir le type de données du dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13599 entries, 0 to 13598
Data columns (total 43 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Unnamed: 0                   13599 non-null  int64
 1   duration                     13599 non-null  int64
 2   protocol_type                13599 non-null  object
 3   service                      13599 non-null  object
 4   flag                         13599 non-null  object
 5   src_bytes                    13599 non-null  int64
 6   dst_bytes                    13599 non-null  int64
 7   land                         13599 non-null  int64
 8   wrong_fragment               13599 non-null  int64
 9   urgent                       13599 non-null  int64
 10  hot                          13599 non-null  int64
 11  num_failed_logins            13599 non-null  int64
 12  logged_in                    13599 non-null  int64
 13  num_compromised              13599 non-null  int64
 14  root_shell                   13599 non-null  int64
 15  su_attempted                 13599 non-null  int64
 16  num_root                     13599 non-null  int64
 17  num_file_creations           13599 non-null  int64
 18  num_shells                   13599 non-null  int64
 19  num_access_files             13599 non-null  int64
 20  num_outbound_cmds            13599 non-null  int64
 21  is_host_login                13599 non-null  int64
 22  is_guest_login               13599 non-null  int64
 23  count                        13599 non-null  int64
 24  srv_count                    13599 non-null  int64
 25  serror_rate                  13599 non-null  float64
 26  srv_serror_rate              13599 non-null  float64
 27  rerror_rate                  13599 non-null  float64
 28  srv_rerror_rate              13599 non-null  float64
 29  same_srv_rate                13599 non-null  float64
 30  diff_srv_rate                13599 non-null  float64
 31  srv_diff_host_rate           13599 non-null  float64
 32  dst_host_count               13599 non-null  int64
 33  dst_host_srv_count           13599 non-null  int64
 34  dst_host_same_srv_rate       13599 non-null  float64
 35  dst_host_diff_srv_rate       13599 non-null  float64
 36  dst_host_same_src_port_rate  13599 non-null  float64
 37  dst_host_srv_diff_host_rate  13599 non-null  float64
 38  dst_host_serror_rate         13599 non-null  float64
 39  dst_host_srv_serror_rate     13599 non-null  float64
 40  dst_host_rerror_rate         13599 non-null  float64
 41  dst_host_srv_rerror_rate     13599 non-null  float64
 42  class                        13599 non-null  object
dtypes: float64(15), int64(24), object(4)
memory usage: 4.3+ MB

In [37]:
data.describe() # Voir les statistiques 
# On remarque que les colonnes 'urgent' 'num_outbound_cmds' 'is_host_login' 
# contiennent uniquement des 0, avec un min = 0 et max = 0 et mean = 0

,Unnamed: 0,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
count,13599.000000,13599.000000,1.359900e+04,1.359900e+04,13599.000000,13599.000000,13599.0,13599.000000,13599.000000,13599.000000,...,13599.000000,13599.000000,13599.000000,13599.000000,13599.000000,13599.000000,13599.000000,13599.000000,13599.000000,13599.000000
mean,12495.645636,182.747776,1.164666e+04,4.352227e+03,0.000074,0.001177,0.0,0.222149,0.001177,0.701669,...,149.209795,187.626664,0.803486,0.041635,0.121749,0.025695,0.021073,0.013594,0.046417,0.044595
std,7333.313621,1371.063164,1.723699e+05,6.941981e+04,0.008575,0.058150,0.0,2.340105,0.043711,0.457542,...,101.645694,94.248057,0.331422,0.130418,0.255221,0.068712,0.122787,0.101307,0.195325,0.191117
min,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6113.500000,0.000000,1.050000e+02,8.100000e+01,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,41.000000,110.000000,0.720000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,12521.000000,0.000000,2.320000e+02,3.700000e+02,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,...,161.000000,255.000000,1.000000,0.000000,0.010000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,18848.000000,0.000000,3.240000e+02,2.009000e+03,0.000000,0.000000,0.0,0.000000,0.000000,1.000000,...,255.000000,255.000000,1.000000,0.020000,0.080000,0.030000,0.000000,0.000000,0.000000,0.000000
max,25186.000000,36613.000000,7.665876e+06,5.131424e+06,1.000000,3.000000,0.0,77.000000,3.000000,1.000000,...,255.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [38]:
# Vérifier si on a des valeurs manquantes
data.isnull().sum()

Unnamed: 0                     0
duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
class                          0
dtype: int64

In [39]:
# Vérifier si on a des données en redondance 
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
13594    False
13595    False
13596    False
13597    False
13598    False
Length: 13599, dtype: bool

In [40]:
# Suppression de la colonne 'urgent' car elle contient que des '0'
data=data.drop('urgent',axis='columns')
data=data.drop('num_outbound_cmds',axis='columns')
data=data.drop('is_host_login',axis='columns')
data.shape # Vérifier si elles ont été supprimées

(13599, 40)

In [41]:
# Conversion des valeures qualitatives en quantitatives
data=pd.get_dummies(data)
data.head() #Vérifier si la conversion a été faite

,Unnamed: 0,duration,src_bytes,dst_bytes,land,wrong_fragment,hot,num_failed_logins,logged_in,num_compromised,...,flag_RSTO,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH,class_anomaly,class_normal
0,0,0,491,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
1,1,0,146,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
2,3,0,232,8153,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,4,0,199,420,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
4,12,0,287,2251,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1

In [42]:
X = data.iloc[:,:-2] # Tout récuperer sauf les 2 derniéres colonnes 
Y = data.iloc[:,-2:] # Récuperer les 2 derniéres colonnes
from sklearn.preprocessing import scale
X=scale(X) 
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,stratify=Y)

In [43]:
def cal(y_test,y_pred): # La fonction prend en paramétre 2 numpy arrays
    vp,vn,fp,fn=0,0,0,0
    for i in range(0,len(y_test)): # Boucle qui parcourt les 2 numpy arrays vu qu'ils ont la même taille 
        #Vrai_Positif
        if((y_test[i,0]==1)&(y_pred[i,0]==1)):
            vp+=1
        #Vrai_Négatif
        elif((y_test[i,1]==1)&(y_pred[i,1]==1)):
            vn+=1
        #Faux_Positif
        elif((y_test[i,1]==1)&(y_pred[i,0]==1)):
            fp+=1
        #Faux_Négatif
        elif((y_test[i,0]==1)&(y_pred[i,1]==1)):
            fn+=1
        
    return vp,vn,fp,fn # Retourner les résultats trouvés

In [44]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
params = {'n_neighbors':[3,5,7,9,11,13,15,17],'metric':['euclidean','manhattan']}
grid=GridSearchCV(KNeighborsClassifier(),params,cv=5) # Chercher les meilleurs paramétres
g=grid.fit(X_train,Y_train)
g.best_params_ # Afficher les meilleurs paramétres

{'metric': 'manhattan', 'n_neighbors': 3}

In [45]:
Knn= KNeighborsClassifier(n_neighbors=3,metric='manhattan')
Knn.fit(X_train,Y_train) 
y_pred=Knn.predict(X_test)

In [46]:
type(y_pred)
#On remarque que le résultat de y_pred est de type numpy array, mais que Y_test est de type dataframe,
#donc pour utiliser notre  fonction on doit convertir pour comparer entre les mêmes data types

numpy.ndarray

In [47]:
#Conversion du dataframe vers numpy array pour pouvoir comparer entre y_test et y_pred dans la fonction
y_test=Y_test.to_numpy()

In [48]:
vp,vn,fp,fn=cal(y_test,y_pred)
prec = vp/(vp+fp)
rap = vp/(vp+fn)
f = (2*prec*rap)/(rap+prec)
print("Precision = "+str(prec)+"\nRappel = "+str(rap)+"\nF1_score = "+str(f))

Precision = 0.9761904761904762
Rappel = 0.9111111111111111
F1_score = 0.9425287356321839

In [49]:
print("Vp = "+str(vp)+"\nVn = "+str(vn)+"\nFp = "+str(fp)+"\nFn = "+str(fn))
# On obtient un trés bon F1 score, donc oui le modéle donne de bons résultats

Vp = 41
Vn = 4034
Fp = 1
Fn = 4